# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'com_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QApplication,QMainWindow
import configparser

class COM_Settings_Window(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_com_settings = QtWidgets.QLabel(self.centralwidget)
        self.label_com_settings.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.label_com_settings.setStyleSheet("font: 500 10pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_com_settings.setObjectName("label_com_settings")
        self.comboBox_bits_per_second = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_bits_per_second.setGeometry(QtCore.QRect(214, 81, 111, 31))
        self.comboBox_bits_per_second.setObjectName("comboBox_bits_per_second")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_bits_per_second.addItem("")
        self.comboBox_data_bits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_data_bits.setGeometry(QtCore.QRect(214, 141, 111, 31))
        self.comboBox_data_bits.setObjectName("comboBox_data_bits")
        self.comboBox_data_bits.addItem("")
        self.comboBox_data_bits.addItem("")
        self.comboBox_data_bits.addItem("")
        self.comboBox_data_bits.addItem("")
        self.comboBox_data_bits.addItem("")
        self.comboBox_parity = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_parity.setGeometry(QtCore.QRect(214, 201, 111, 31))
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_stop_bits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stop_bits.setGeometry(QtCore.QRect(214, 261, 111, 31))
        self.comboBox_stop_bits.setObjectName("comboBox_stop_bits")
        self.comboBox_stop_bits.addItem("")
        self.comboBox_stop_bits.addItem("")
        self.comboBox_stop_bits.addItem("")
        self.comboBox_flow_control = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_flow_control.setGeometry(QtCore.QRect(214, 321, 111, 31))
        self.comboBox_flow_control.setObjectName("comboBox_flow_control")
        self.comboBox_flow_control.addItem("")
        self.comboBox_flow_control.addItem("")
        self.comboBox_flow_control.addItem("")
        self.label_bits_per_second = QtWidgets.QLabel(self.centralwidget)
        self.label_bits_per_second.setGeometry(QtCore.QRect(102, 79, 121, 31))
        self.label_bits_per_second.setStyleSheet("font: 500 8pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_bits_per_second.setObjectName("label_bits_per_second")
        self.label_data_bits = QtWidgets.QLabel(self.centralwidget)
        self.label_data_bits.setGeometry(QtCore.QRect(144, 140, 71, 31))
        self.label_data_bits.setStyleSheet("font: 500 8pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_data_bits.setObjectName("label_data_bits")
        self.label_parity = QtWidgets.QLabel(self.centralwidget)
        self.label_parity.setGeometry(QtCore.QRect(166, 199, 51, 31))
        self.label_parity.setStyleSheet("font: 500 8pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_parity.setObjectName("label_parity")
        self.label_stop_bits = QtWidgets.QLabel(self.centralwidget)
        self.label_stop_bits.setGeometry(QtCore.QRect(144, 259, 71, 31))
        self.label_stop_bits.setStyleSheet("font: 500 8pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_stop_bits.setObjectName("label_stop_bits")
        self.label_flow_control = QtWidgets.QLabel(self.centralwidget)
        self.label_flow_control.setGeometry(QtCore.QRect(120, 320, 91, 31))
        self.label_flow_control.setStyleSheet("font: 500 8pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_flow_control.setObjectName("label_flow_control")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(190, 410, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_com_settings.setText(_translate("MainWindow", "COM settings:"))
        self.comboBox_bits_per_second.setItemText(0, _translate("MainWindow", "75"))
        self.comboBox_bits_per_second.setItemText(1, _translate("MainWindow", "110"))
        self.comboBox_bits_per_second.setItemText(2, _translate("MainWindow", "134"))
        self.comboBox_bits_per_second.setItemText(3, _translate("MainWindow", "150"))
        self.comboBox_bits_per_second.setItemText(4, _translate("MainWindow", "300"))
        self.comboBox_bits_per_second.setItemText(5, _translate("MainWindow", "600"))
        self.comboBox_bits_per_second.setItemText(6, _translate("MainWindow", "1200"))
        self.comboBox_bits_per_second.setItemText(7, _translate("MainWindow", "1800"))
        self.comboBox_bits_per_second.setItemText(8, _translate("MainWindow", "2400"))
        self.comboBox_bits_per_second.setItemText(9, _translate("MainWindow", "4800"))
        self.comboBox_bits_per_second.setItemText(10, _translate("MainWindow", "7200"))
        self.comboBox_bits_per_second.setItemText(11, _translate("MainWindow", "9600"))
        self.comboBox_bits_per_second.setItemText(12, _translate("MainWindow", "14400"))
        self.comboBox_bits_per_second.setItemText(13, _translate("MainWindow", "19200"))
        self.comboBox_bits_per_second.setItemText(14, _translate("MainWindow", "38400"))
        self.comboBox_bits_per_second.setItemText(15, _translate("MainWindow", "57600"))
        self.comboBox_bits_per_second.setItemText(16, _translate("MainWindow", "115200"))
        self.comboBox_bits_per_second.setItemText(17, _translate("MainWindow", "128000"))


        config = configparser.ConfigParser()
        config.read('configfile.ini')
        bits_per_second = config['COM settings']['bits per second']

        self.comboBox_bits_per_second.setCurrentText(bits_per_second)

        self.comboBox_data_bits.setItemText(0, _translate("MainWindow", "4"))
        self.comboBox_data_bits.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_data_bits.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_data_bits.setItemText(3, _translate("MainWindow", "7"))
        self.comboBox_data_bits.setItemText(4, _translate("MainWindow", "8"))

        data_bits = config['COM settings']['data bits']
        self.comboBox_data_bits.setCurrentText(data_bits)

        self.comboBox_parity.setItemText(0, _translate("MainWindow", "Even"))
        self.comboBox_parity.setItemText(1, _translate("MainWindow", "Odd"))
        self.comboBox_parity.setItemText(2, _translate("MainWindow", "None"))
        self.comboBox_parity.setItemText(3, _translate("MainWindow", "Mark"))
        self.comboBox_parity.setItemText(4, _translate("MainWindow", "Space"))

        parity = config['COM settings']['parity']
        self.comboBox_parity.setCurrentText(parity)

        self.comboBox_stop_bits.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stop_bits.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stop_bits.setItemText(2, _translate("MainWindow", "2"))

        stop_bits = config['COM settings']['stop bits']
        self.comboBox_stop_bits.setCurrentText(stop_bits)

        self.comboBox_flow_control.setItemText(0, _translate("MainWindow", "Xon / Xoff"))
        self.comboBox_flow_control.setItemText(1, _translate("MainWindow", "Hardware"))
        self.comboBox_flow_control.setItemText(2, _translate("MainWindow", "None"))

        flow_control_bits = config['COM settings']['flow control']
        self.comboBox_flow_control.setCurrentText(flow_control_bits)

        self.label_bits_per_second.setText(_translate("MainWindow", "Bits per second:"))
        self.label_data_bits.setText(_translate("MainWindow", "Data bits:"))
        self.label_parity.setText(_translate("MainWindow", "Parity:"))
        self.label_stop_bits.setText(_translate("MainWindow", "Stop bits:"))
        self.label_flow_control.setText(_translate("MainWindow", "Flow control:"))

        self.buttonBox.accepted.connect(self.push_ok)
        self.buttonBox.rejected.connect(self.push_cancel)

    def push_ok(self):
        config = configparser.ConfigParser()
        config.read('configfile.ini')
        config.set('COM settings', 'Bits per second', self.comboBox_bits_per_second.currentText())
        config.set('COM settings', 'Data bits', self.comboBox_data_bits.currentText())
        config.set('COM settings', 'Parity', self.comboBox_parity.currentText())
        config.set('COM settings', 'Stop bits', self.comboBox_stop_bits.currentText())
        config.set('COM settings', 'Flow control', self.comboBox_flow_control.currentText())
        with open('configfile.ini', 'w') as configfile:
            config.write(configfile)

    def push_cancel(self):
        config = configparser.ConfigParser()
        config.read('configfile.ini')
        self.comboBox_bits_per_second.setCurrentText(config['COM settings']['bits per second'])
        self.comboBox_data_bits.setCurrentText(config['COM settings']['data bits'])
        self.comboBox_parity.setCurrentText(config['COM settings']['parity'])
        self.comboBox_stop_bits.setCurrentText(config['COM settings']['stop bits'])
        self.comboBox_flow_control.setCurrentText(config['COM settings']['flow control'])



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = COM_Settings_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
