# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QApplication,QMainWindow
import configparser
class Function_Button(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_select_button = QtWidgets.QLabel(self.centralwidget)
        self.label_select_button.setGeometry(QtCore.QRect(40, 20, 181, 41))
        self.label_select_button.setStyleSheet("font: 500 16pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_select_button.setObjectName("label_select_button")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(40, 90, 51, 28))
        self.pushButton_1.setStyleSheet("font: 75 10pt \"Tahoma\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 140, 51, 28))
        self.pushButton_2.setStyleSheet("font: 75 10pt \"Tahoma\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 190, 51, 28))
        self.pushButton_3.setStyleSheet("font: 75 10pt \"Tahoma\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 240, 51, 28))
        self.pushButton_4.setStyleSheet("font: 75 10pt \"Tahoma\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_select_a_command_for_the_button = QtWidgets.QLabel(self.centralwidget)
        self.label_select_a_command_for_the_button.setGeometry(QtCore.QRect(40, 280, 451, 41))
        self.label_select_a_command_for_the_button.setStyleSheet("font: 500 16pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_select_a_command_for_the_button.setObjectName("label_select_a_command_for_the_button")
        self.label_command_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_command_1.setGeometry(QtCore.QRect(110, 80, 181, 41))
        self.label_command_1.setStyleSheet("font: 500 10pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_command_1.setObjectName("label_command_1")
        self.pushButton_Iout_q = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Iout_q.setGeometry(QtCore.QRect(40, 350, 81, 28))
        self.pushButton_Iout_q.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_Iout_q.setObjectName("pushButton_Iout_q")
        self.pushButton_Vout_q = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Vout_q.setGeometry(QtCore.QRect(130, 350, 81, 28))
        self.pushButton_Vout_q.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_Vout_q.setObjectName("pushButton_Vout_q")
        self.pushButton_STATUS_q = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_STATUS_q.setGeometry(QtCore.QRect(220, 350, 81, 28))
        self.pushButton_STATUS_q.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_STATUS_q.setObjectName("pushButton_STATUS_q")
        self.pushButton_IDN_q = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_IDN_q.setGeometry(QtCore.QRect(310, 350, 81, 28))
        self.pushButton_IDN_q.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_IDN_q.setObjectName("pushButton_IDN_q")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(310, 390, 81, 28))
        self.pushButton_9.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 390, 81, 28))
        self.pushButton_10.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 390, 81, 28))
        self.pushButton_11.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 390, 81, 28))
        self.pushButton_12.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(310, 430, 81, 28))
        self.pushButton_13.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(130, 430, 81, 28))
        self.pushButton_14.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(40, 430, 81, 28))
        self.pushButton_15.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(220, 430, 81, 28))
        self.pushButton_16.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(310, 470, 81, 28))
        self.pushButton_17.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(130, 470, 81, 28))
        self.pushButton_18.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(40, 470, 81, 28))
        self.pushButton_19.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(220, 470, 81, 28))
        self.pushButton_20.setStyleSheet("font: 10pt \"Tahoma\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(310, 560, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_info.setGeometry(QtCore.QRect(20, 560, 93, 28))
        self.pushButton_info.setStyleSheet("font: 8pt \"Tahoma\";")
        self.pushButton_info.setObjectName("pushButton_info")
        self.label_command_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_command_2.setGeometry(QtCore.QRect(110, 130, 181, 41))
        self.label_command_2.setStyleSheet("font: 500 10pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_command_2.setObjectName("label_command_2")
        self.label_command_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_command_3.setGeometry(QtCore.QRect(110, 180, 181, 41))
        self.label_command_3.setStyleSheet("font: 500 10pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_command_3.setObjectName("label_command_3")
        self.label_command_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_command_4.setGeometry(QtCore.QRect(110, 230, 181, 41))
        self.label_command_4.setStyleSheet("font: 500 10pt \"Tahoma\";\n"
"color: rgb(0, 0, 255);")
        self.label_command_4.setObjectName("label_command_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_select_button.setText(_translate("MainWindow", "Select button:"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.label_select_a_command_for_the_button.setText(_translate("MainWindow", "Select a command for the button:"))
        self.pushButton_Iout_q.setText(_translate("MainWindow", "Iout?"))
        self.pushButton_Vout_q.setText(_translate("MainWindow", "Vout?"))
        self.pushButton_STATUS_q.setText(_translate("MainWindow", "STATUS?"))
        self.pushButton_IDN_q.setText(_translate("MainWindow", "IDN?"))
        self.pushButton_9.setText(_translate("MainWindow", "none"))
        self.pushButton_10.setText(_translate("MainWindow", "none"))
        self.pushButton_11.setText(_translate("MainWindow", "none"))
        self.pushButton_12.setText(_translate("MainWindow", "none"))
        self.pushButton_13.setText(_translate("MainWindow", "none"))
        self.pushButton_14.setText(_translate("MainWindow", "none"))
        self.pushButton_15.setText(_translate("MainWindow", "none"))
        self.pushButton_16.setText(_translate("MainWindow", "none"))
        self.pushButton_17.setText(_translate("MainWindow", "none"))
        self.pushButton_18.setText(_translate("MainWindow", "none"))
        self.pushButton_19.setText(_translate("MainWindow", "none"))
        self.pushButton_20.setText(_translate("MainWindow", "none"))
        self.pushButton_info.setText(_translate("MainWindow", "Info"))


        config = configparser.ConfigParser()
        config.read('configfile.ini')

        command_1 = config['function button']['1']
        self.label_command_1.setText(_translate("MainWindow", command_1))

        command_2 = config['function button']['2']
        self.label_command_2.setText(_translate("MainWindow", command_2))

        command_3 = config['function button']['3']
        self.label_command_3.setText(_translate("MainWindow", command_3))

        command_4 = config['function button']['4']
        self.label_command_4.setText(_translate("MainWindow", command_4))

        self.pushButton_1.clicked.connect(self.push_button_1)
        self.pushButton_2.clicked.connect(self.push_button_2)
        self.pushButton_3.clicked.connect(self.push_button_3)
        self.pushButton_4.clicked.connect(self.push_button_4)

        self.pushButton_Iout_q.clicked.connect(self.push_button_Iout_q)
        self.pushButton_Vout_q.clicked.connect(self.push_button_Vout_q)
        self.pushButton_STATUS_q.clicked.connect(self.push_STATUS_q)
        self.pushButton_IDN_q.clicked.connect(self.push_IDN_q)


        self.buttonBox.accepted.connect(self.push_ok)
        self.buttonBox.rejected.connect(self.push_cancel)

    def push_button_1(self):
        self.selected_button = "1"
    def push_button_2(self):
        self.selected_button = "2"
    def push_button_3(self):
        self.selected_button = "3"
    def push_button_4(self):
        self.selected_button = "4"



    def push_button_Iout_q(self):
        if self.selected_button == "1":
            self.label_command_1.setText("Iout?")
        if self.selected_button == "2":
            self.label_command_2.setText("Iout?")
        if self.selected_button == "3":
            self.label_command_3.setText("Iout?")
        if self.selected_button == "4":
            self.label_command_4.setText("Iout?")
    def push_button_Vout_q(self):
        if self.selected_button == "1":
            self.label_command_1.setText("Vout?")
        if self.selected_button == "2":
            self.label_command_2.setText("Vout?")
        if self.selected_button == "3":
            self.label_command_3.setText("Vout?")
        if self.selected_button == "4":
            self.label_command_4.setText("Vout?")
    def push_STATUS_q(self):
        if self.selected_button == "1":
            self.label_command_1.setText("STATUS?")
        if self.selected_button == "2":
            self.label_command_2.setText("STATUS?")
        if self.selected_button == "3":
            self.label_command_3.setText("STATUS?")
        if self.selected_button == "4":
            self.label_command_4.setText("STATUS?")
    def push_IDN_q(self):
        if self.selected_button == "1":
            self.label_command_1.setText("IDN?")
        if self.selected_button == "2":
            self.label_command_2.setText("IDN?")
        if self.selected_button == "3":
            self.label_command_3.setText("IDN?")
        if self.selected_button == "4":
            self.label_command_4.setText("IDN?")

    def push_ok(self):
        config = configparser.ConfigParser()
        config.read('configfile.ini')
        config.set('function button','1',self.label_command_1.text())
        config.set('function button','2',self.label_command_2.text())
        config.set('function button','3',self.label_command_3.text())
        config.set('function button','4',self.label_command_4.text())
        with open('configfile.ini', 'w') as configfile:
            config.write(configfile)


    def push_cancel(self):
        config = configparser.ConfigParser()
        config.read('configfile.ini')
        self.label_command_1.setText(config['function button']['1'])
        self.label_command_2.setText(config['function button']['2'])
        self.label_command_3.setText(config['function button']['3'])
        self.label_command_4.setText(config['function button']['4'])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Function_Button()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
